name: Latest Release Build
on:
  release:
    types:
      - published
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: 'recursive'
      - uses: c-hive/gha-yarn-cache@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install modules
        run: yarn
      - name: Build Chrome
        run: |
          VERSION=$(echo -n "${{ github.ref }}" | sed 's/[refs\/tagv]//g' | sed 's/-.*//') yarn build:chrome
          yarn package
      - name: Upload Chrome package to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/YtcFilter-Chrome.zip
          asset_name: YtcFilter-Chrome.zip
          tag: ${{ github.ref }}
          overwrite: true
      - name: Build Firefox
        run: |
          VERSION=$(echo -n "${{ github.ref }}" | sed 's/[refs\/tagv]//g' | sed 's/-.*//') yarn build:firefox
          yarn package
      - name: Upload Firefox package to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/YtcFilter-Firefox.zip
          asset_name: YtcFilter-Firefox.zip
          tag: ${{ github.ref }}
          overwrite: true
